import type { NextPage } from 'next'
import Head from 'next/head'

//Components
import Header from '../components/Header'
import Hero from '../components/Hero'
import About from '../components/About'
import Experience from '../components/Experience'
import Skills from '../components/Skills'
import Projects from '../components/Projects'


const Home: NextPage = () => {
  return (
    <div className='bg-[rgb(36,36,36)] h-screen snap-y snap-mandatory overflow-scroll z-0'>
      <Head>
        <title>Hans-Eirik Breyholtz-Mott's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Header/>
      { /* Hero */}
      <section id='hero' className='snap-start'>
        <Hero/>
      </section>
      {/* About */}
      <section id='about' className='snap-center'>
        <About />
      </section>
      {/* Experience */}
      <section id='experience' className='snap-center'>
        <Experience />
      </section>
      {/* Skills */}
      <section id='skills' className='snap-start'>
        <Skills />
      </section>
      {/* Projects */}
        <section id='projects' className='snap-center'>
          <Projects />
        </section>
      {/* Contact Me */}

      
    </div>
  )
}

export default Home
